//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_register
    {
        public int admin_Id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public string admin_email { get; set; }
        public string admin_contact { get; set; }
        public string admin_profilepic { get; set; }
    }
}
