//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_Id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> offer_id { get; set; }
        public string with_without_driver { get; set; }
        public string mode_of_payment { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string pickuplocation { get; set; }
        public string pickupaddress { get; set; }
        public string droplocation { get; set; }
        public string dropaddress { get; set; }
        public string no_of_days { get; set; }
        public string bill_amount { get; set; }
        public string driver_charge { get; set; }
        public string net_amount_pay { get; set; }
        public string description { get; set; }
        public string status { get; set; }
    
        public virtual car_type car_type { get; set; }
        public virtual User User { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
