//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car_type()
        {
            this.Packages = new HashSet<Package>();
            this.bookings = new HashSet<booking>();
        }
    
        public int car_Id { get; set; }
        public Nullable<int> Brand_id { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Fuel_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public string car_name { get; set; }
        public string images { get; set; }
        public Nullable<int> No_of_seats { get; set; }
        public Nullable<int> Manufacture { get; set; }
        public string Car_number { get; set; }
        public Nullable<int> Per_day_price { get; set; }
        public string Descriptiton { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual car_category car_category { get; set; }
        public virtual Fuel_Type Fuel_Type { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
    }
}
