//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Driver_ID_ { get; set; }
        public string Driver_Image { get; set; }
        public string Driver_Licence { get; set; }
        public string Driver_Name { get; set; }
        public Nullable<int> Driver_Age { get; set; }
        public string Driver_Gender { get; set; }
        public string Driver_ContactNo { get; set; }
        public string Driver_Email_ { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public string Salary { get; set; }
        public string Experience { get; set; }
        public string Driver_Address { get; set; }
        public Nullable<int> City_id { get; set; }
    
        public virtual City City { get; set; }
    }
}
