//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carrentalEntities : DbContext
    {
        public carrentalEntities()
            : base("name=carrentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Admin_register> Admin_register { get; set; }
        public virtual DbSet<car_category> car_category { get; set; }
        public virtual DbSet<Fuel_Type> Fuel_Type { get; set; }
        public virtual DbSet<car_type> car_type { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<service_category> service_category { get; set; }
        public virtual DbSet<service> services { get; set; }
    }
}
