//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int package_Id { get; set; }
        public Nullable<int> carid { get; set; }
        public string package_name { get; set; }
        public string package_charges { get; set; }
        public Nullable<System.DateTime> package_date { get; set; }
        public string status { get; set; }
    
        public virtual car_type car_type { get; set; }
    }
}
