//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class service
    {
        public int sId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobileno { get; set; }

        [DisplayName("date")]
        [DataType(DataType.Date, ErrorMessage = "Date only")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> pickup { get; set; }
        public Nullable<int> service1 { get; set; }
        public string message { get; set; }
    
        public virtual City City { get; set; }
        public virtual service_category service_category { get; set; }
    }
}
